### ISSUE TITLE
只有正面没有反面？

### ISSUE THREAD

**Issue by lyluoyuan** [KevinGong2013/ChineseIDCardOCR#10]

**Comment by KevinGong2013** [comment]
目前正面也只有 `身份证号码` 的识别, 打算用 `CNN` 替换  `FFNN`网络，替换完成以后正反面都不是问题啦。
不过最近比较忙，可能要稍微等等。

**Comment by KevinGong2013** [comment]
已经用`CNN`替换`FNN` 了， 如果需要可以自己训练识别地址的神经网络了～
