### ISSUE TITLE
大神会写android的身份证识别吗

### ISSUE THREAD

**Issue by Droidrzy** [KevinGong2013/ChineseIDCardOCR#13]

**Comment by Crazy-Steven** [comment]
用腾讯的优图https://open.youtu.qq.com/welcome/developer#/api-image-ocr-idcard有demo可以下载看看

**Comment by KevinGong2013** [comment]
安卓建议使用云服务会比较好一点， 因为安卓的设备性能层次不齐，体验可能比较差。
