### ISSUE TITLE
libexidcardios

### ISSUE THREAD

**Issue by iOSzyz** [KevinGong2013/ChineseIDCardOCR#14]
这个库用到的原理是什么呢？我搜到用google开源的  TesseractOCRiOS 感觉比这个慢好多。。。能否透露下原理

**Comment by KevinGong2013** [comment]
这是纯Swift 实现的 `FFNN前馈神经网络`。 现在`Apple`发布了新的sdk， 准备有时间了用 `CNN卷积神经网络` 重写一下
