### ISSUE TITLE
您好，iOS11以下使用不了,有什么办法吗？

### ISSUE THREAD

**Issue by github410117** [KevinGong2013/ChineseIDCardOCR#16]
知道库中有些东西是iOS11独有的，但是目前iOS11市场占有率还没那么大，项目需要兼顾9-11，请问有没有什么办法处理呢，期待您的回复！谢谢

**Comment by KevinGong2013** [comment]
iOS11 以下 用一些付费的网络识别服务好了。

**Comment by github410117** [comment]
那请问有什么推荐吗？在网上搜索了一会，不知道哪个靠谱

**Comment by KevinGong2013** [comment]
https://market.aliyun.com/products/?sre=s2&keyword=身份证识别#ymk=%7B%22keywords%22:%22身份证识别%22,%22pageSize%22:10,%22saleMode%22:0,%22pageIndex%22:1,%22categoryId%22:%22%22%7D

**Comment by github410117** [comment]
万分感谢您的回答！谢谢！
我将其Close
