### ISSUE TITLE
按照图片比例进行截取小图片，然后根据FFNN学习算法识别，感觉有点鸡肋。

### ISSUE THREAD

**Issue by RobinChao** [KevinGong2013/ChineseIDCardOCR#3]
截取小图片的方式个人感觉有点不易拓展，因为不同的证件或者其他的比例不尽相同，要是截取再识别的话难度还是蛮大的。为何不直接使用opencv进行图片的预处理，然后进行识别呢？

个人看法，见谅~

**Comment by KevinGong2013** [comment]
嗯，目前这种处理小图片的方式只适用于英文字母和数字是有点局限性。 我之前也没有做过类似的项目，我回头去研究一下opencv 看看能不能完美的融合进来。

总之，谢谢你的建议。

**Comment by RobinChao** [comment]
@KevinGong2013 有个图片识别前的预处理论文，不知道是否会有帮助。[https://github.com/bigdig/OCR/blob/master/doc/%E8%BD%A6%E7%89%8C%E8%AF%86%E5%88%AB%E9%A2%84%E5%A4%84%E7%90%86%E4%B8%AD%E7%9A%84%E4%BA%8C%E5%80%BC%E5%8C%96%E5%8F%8A%E5%80%BE%E6%96%9C%E7%9F%AB%E6%AD%A3%E7%AE%97%E6%B3%95.pdf](车牌识别预处理中的二值化及倾斜矫正算法)

**Comment by KevinGong2013** [comment]
刚才看了一下 `opencv` 的framework有160M 是不是有点太大了。。

**Comment by any35** [comment]
那上框架所有的东西加起来的大小, 生成的文件大约只有几M, 另外它的内核是按库分类且可以裁剪的, 对体积有要求可以进一步裁剪. 在ios和android中用不是问题.

**Comment by any35** [comment]
另外opencv对手机GPU支持不完善, 主要靠CPU运算, 主要考虑性能问题, 够不够自己评估一下吧.

**Comment by a11enwong** [comment]
我觉得不要扯太远什么都要支持，聚焦银行卡、身份证就足够了

**Comment by KevinGong2013** [comment]
@a11enwong  所有的这种识别原理都是一样的。只需要用不同的样本训练神经网络就可以了。

现在的主要任务是图片的预处理，和识别网络替换，我最近工作比较忙。等这几天忙完以后，我应该会马上更新这个项目。

谢谢你的意见。
