### ISSUE TITLE
能否实现自动裁剪？

### ISSUE THREAD

**Issue by Drshu** [KevinGong2013/ChineseIDCardOCR#9]
您的项目做的不错，但是我现在主要是要一个可以自动裁剪身份证的库，不知道这个项目能不能做到？也就是我手机对准之后，自动裁剪出大概的边框，但是不用识别

**Comment by KevinGong2013** [comment]
这个库不可以。但是我可以给你一点建议。
在手机取景器对准身份的时候用 `Sobel边缘检测` 之类的算法实现。

自动裁剪这个功能，以后有时间我也会添加到这个库当中。如果你实现了能开源一下最好啦。

**Comment by Drshu** [comment]
好的，我尝试一下，谢谢你！

**Comment by willard-yuan** [comment]
@Drshu 可以采用object detection的方式框出身份证的位置，不过这种方式不是很精确，比较精确是采用line detection，不过背景的干扰对line detection影像很大。

**Comment by Drshu** [comment]
@willard-yuan 请问有没有一个Swift或者OC的简单实现?因为没有接触过这一方面的东西，还有就是我的目的是要其识别是一张卡片（最好能够识别是身份证，但是没有检测的思路）然后大致裁下来就行了，因为我识别模块准备在后端实现，所以保证清晰度和大小就OK，有没有比较容易实现的方案？谢谢

**Comment by KevinGong2013** [comment]
有静态库可以用。`OpenCV`
